### ISSUE TITLE
Date de dernière action

### ISSUE THREAD

**Issue by laarmen** [Geekin-side/LLDC#3]
Submitted by @Ultim4T0m 

La date de dernière action est gérée par l'EventListener _KernelListener_

Plutôt que de vérifier le type du contrôleur, il faudrait faire un test sur une variable _updateDateAction_, qui serait par défaut à true, mais que l'on passerait à false uniquement dans les routes que l'on veut.

Exemple : 

``` yaml
json_notification:
    pattern: /notification
    defaults: { _controller: "LLDCBundle:Webservice\\Notification:notification", updateDateAction: false }
    requirements:
        _method:  GET
    options:
        expose: true
```

À voir si c'est faisable.

---

@laarmen

Pas une variable, une méthode. Si on peut appeler une méthode, bien sûr. C'est sale d'accéder à une variable statique à travers une instance.

---

@Ultim4T0m 
Sinon, mieux, je pense qu'on peut utiliser la partie "options" de la définition de la route, pour créer nos options persos... Une méthode, non, ça m'étonnerait, c'est de l'yml là
